###IMPORT FILE

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

1.13.1+cu116


###Introduction

In [ ]:
##Introduction to Tensors
###Creating Tensors

###Scalar

In [ ]:
scalar = torch.tensor(7)
scalar
#Scalar is 0 dimension

tensor(7)

###Vector

In [ ]:
vector = torch.tensor([7,7])
vector
#Vector is 1 dimension

tensor([7, 7])

###MATRIX

In [ ]:
MATRIX = torch.tensor([[7,8],[9,10]])
MATRIX[0]

tensor([7, 8])

###TENSOR

In [ ]:
#Tensor
TENSOR = torch.tensor([[[2,3,4],[3,4,5],[4,5,6]]])
TENSOR.shape

torch.Size([1, 3, 3])

###RANDOM TENSOR

Random Tensor are important because they represent the first input given by the machine learning / deep learning model and then adjust the random tensor numbers to represent a better data.

Start with random number -> look at data -> update random numbers -> update random numbers.

In [ ]:
#Create a random tensor of size(3,4)
random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.3130, 0.8187, 0.9884, 0.2315],
        [0.5773, 0.6028, 0.1259, 0.0701],
        [0.2561, 0.6952, 0.4085, 0.1333]])

In [ ]:
#Create a random tensor with a similar shape to an image tensor
random_image_tensor = torch.rand(size = (3,224,224)) #height ,width ,color (R,G,B)
#size represent dimension (a,b,c) mean 3 dimensions 
random_image_tensor.shape

torch.Size([3, 224, 224])

###ZEROES AND ONES

In [ ]:
zero_tensor = torch.zeros(3,4)
zero_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
one = torch.ones(3,4)
one

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

###Create a range of tensors and tensors like

In [ ]:
#Use torch.arange()
one_to_ten = torch.arange(1,11)
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
step = torch.arange(start = 0, end = 1000, step = 123)
step

tensor([  0, 123, 246, 369, 492, 615, 738, 861, 984])

In [ ]:
#Create a tensors like
ten_zero = torch.zeros_like(input=one_to_ten)
ten_zero

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

##Tensor Datatype

**Note:** 3 Errors you will get with datatype in pytorch and deeplearning:

1. Tensors not right datatype - to get dataype from tensor, use `tensor.dtype`
2. Tensors not right shape - to get a shape from tensor, use `tensor.shape`
3. Tensors not on right device - to get a device from tensor, use `tensor.device`


In [ ]:
#Float 32-tensor
#datatype of tensor(float32, float16, etc)
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                               dtype=None,
                               device=None, ##tensor device of the GPU, TPU(cuda, etc)
                               requires_grad=False) #Wether or not track gradient with this tensors operation
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor.dtype

torch.float16

In [ ]:
int_32_tensor = torch.tensor([3,6,9], dtype = torch.int32)
int_32_tensor

tensor([3, 6, 9], dtype=torch.int32)

In [ ]:
int_32_tensor.dtype

torch.int32

In [ ]:
float_16_tensor * int_32_tensor

tensor([ 9., 36., 81.], dtype=torch.float16)

##Getting Information from Tensor(Tensor Attribute)
1. Tensors not right datatype - to get dataype from tensor, use tensor.dtype
2. Tensors not right shape - to get a shape from tensor, use tensor.shape
3. Tensors not on right device - to get a device from tensor, use tensor.device

In [ ]:
#Create tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.5464, 0.2569, 0.7313, 0.6242],
        [0.4812, 0.6673, 0.5258, 0.5663],
        [0.1620, 0.6520, 0.4258, 0.5492]])

In [ ]:
#Find detail of a tensor
print(some_tensor)
print(f"Datatype of tensors : {some_tensor.dtype}")
print(f"Shape of tensor : {some_tensor.size()}")
print(f"Device of tensor : {some_tensor.device}")


tensor([[0.5464, 0.2569, 0.7313, 0.6242],
        [0.4812, 0.6673, 0.5258, 0.5663],
        [0.1620, 0.6520, 0.4258, 0.5492]])
Datatype of tensors : torch.float32
Shape of tensor : torch.Size([3, 4])
Device of tensor : cpu


###Manipulating Tensors(Tensor Operations)

Tensor Operation include:
* Addition
* Substraction
* Multiplication (element-wise)
* Division
* Matrix Multiplication

In [ ]:
#Create a Tensor and add 10 to it
tensor = torch.tensor([1,2,3])
torch.add(tensor,10) #same function
tensor + 10

tensor([11, 12, 13])

In [ ]:
#Multiply a tensor
tensor * 10 
torch.mul(tensor,10) #same function

tensor([10, 20, 30])

In [ ]:
#Substract tensor
tensor - 10

tensor([-9, -8, -7])

##Matrix Multiplication

Two ways of performing matrix multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product {a . b})

Two main rule of performing matrix multiplication:
1. The **Inner dimension** must match:
- (3,2) (2,3) will work.
- (2,3) (2,3) won't work.
2. The resulting matrix has the shape of **outer dimension**"
- (3,2) (2,3) -> result shape : (3,3)
- (2,3) (3,2) -> result shape : (2,2)


In [ ]:
#Element-wise Multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")
#can use operation like tensor @ tensor

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [ ]:
%%time
#Matrix Multiplication
torch.matmul(tensor,tensor) ##this is the fastest to calculate matrix multiplication
#torch.mm is the same as torch.matmul
torch.matmul(tensor,tensor)

CPU times: user 4.86 ms, sys: 0 ns, total: 4.86 ms
Wall time: 13.7 ms


tensor(14)

In [ ]:
%%time
torch.matmul(torch.rand(3,2),torch.rand(2,3))

CPU times: user 3.8 ms, sys: 128 µs, total: 3.93 ms
Wall time: 20.5 ms


tensor([[0.3258, 0.1443, 0.3243],
        [1.1914, 0.5270, 1.1860],
        [0.4429, 0.1944, 0.4411]])

To fix tensor shapes, we can manipulate using transpose.

In [ ]:
tensor_a = torch.rand(3,2)
tensor_b = torch.rand(3,2)
tensor_b = tensor_b.T #For transpose
torch.mm(tensor_a,tensor_b) ##from (3,2) @ (3,2) -> (3,2) @ (2,3)

tensor([[0.5459, 0.1006, 0.2524],
        [0.5107, 0.0875, 0.2199],
        [0.5679, 0.0773, 0.1958]])

##Finding the min, max, mean, sum, etc (aggregation)

In [ ]:
#Create a tensor

x = torch.arange(0,101,10)
x, x.dtype

(tensor([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]), torch.int64)

In [ ]:
#find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
#find the max
torch.max(x), x.max()

(tensor(100), tensor(100))

In [ ]:
#Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean() #MEAN change type from int to floating point / long (float32)

(tensor(50.), tensor(50.))

In [ ]:
#Find the sum
torch.sum(x), x.sum()

(tensor(550), tensor(550))

##Find the positional min and max

In [ ]:
x.argmin(), x.argmax() ##index min value & index max value

(tensor(0), tensor(10))

##RESHAPING, STACKING, SQUEEZING, AND UNSQUEEZING TENSORS

* Reshape - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other (vstack) or side by side(hstack)
* Squeeze - remove all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input dimensions permuted (swapped) in a certain dimension way

In [ ]:
#example
x = torch.arange(1,11,1)
x, x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [ ]:
#Add an extra dimension

x_reshaped = x.reshape(1,10) #reshape must always have equal to original size
x_reshaped, x_reshaped.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
#Change the view
z = x.view(1,10) #Z and X share same memory, changing Z means changing X as well.
z, z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [ ]:
#Change Z if it change X as well
z[:,0] = 5
z,x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [ ]:
#Stack tensor of each other
x_stacked = torch.stack([x,x,x,x],dim=0)
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [ ]:
#torch_squeeze
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

x_reshaped = x_reshaped.squeeze()

print(f"Tensor now : {x_reshaped}")
print(f"Shape now : {x_reshaped.shape}")

Previous tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
Previous shape : torch.Size([1, 10])
Tensor now : tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Shape now : torch.Size([10])


In [ ]:
#torch_unSqueeze

print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape : {x_reshaped.shape}")

x_reshaped = x_reshaped.unsqueeze(dim=0)

print(f"Tensor now : {x_reshaped}")
print(f"Shape now : {x_reshaped.shape}")

Previous tensor: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Previous shape : torch.Size([10])
Tensor now : tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
Shape now : torch.Size([1, 10])


In [ ]:
#torch_permute

x_original = torch.rand(size=(224,224,3)) #image data height, width, colour channel

#permute the original tensor to rearrange axis of dimension / order of the dimension
x_permuted = x_original.permute(2,0,1) #shift index 2->0, 0->1, 1->2
x_permuted.shape

torch.Size([3, 224, 224])

##Indexing (Selecting Data from Tensors)

In [ ]:
#Create Tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [ ]:
#Index on new tensor all dimension

x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
#Index on new tensor (dim=1)
x[0][0]

tensor([1, 2, 3])

In [ ]:
#Index on new tensor last dimension
x[0][0][0]

tensor(1)

In [ ]:
#use ":" to select "all" dimension
x[:, :, 1] #grab all dimension 0 and 1, and only grab dimension 2 of index 1

tensor([[2, 5, 8]])

##Pytorch tensors  & NumPy

Numpy is a popular scientific python numerical computer library.
And because of this, Pytorch has functionality to interact with it.

* Data in NumPy, want in Pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch tensor -> NumPy -> `torch.Tensor.numPy()`

In [ ]:
#NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0,8.0)
tensor = torch.from_numpy(array) ##warning, when converting from numpy to pytorch, pytorch reflect numpy's default dataType of float64 unless specified otherwise. Must convert it to float32 for torch
array,tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
tensor.dtype 

torch.float32

##Reproducibility (Trying to take random of random)

How Neural Network works:

`start with random numbers -> tensor operations -> update random numbers to try and make them of the data -> again -> again -> ...`

To reduce randomness in neural networks and pyTorch comes the concept of **random seed**.
Essentially what the random seed does in "flavour" the randomness.

In [ ]:
random_tensor_a = torch.rand(3,4)
random_tensor_b = torch.rand(3,4)
print(random_tensor_a)
print(random_tensor_b)
print(random_tensor_a == random_tensor_b)

tensor([[0.0096, 0.9639, 0.6639, 0.8781],
        [0.4634, 0.3716, 0.8736, 0.0981],
        [0.6652, 0.5529, 0.8337, 0.6354]])
tensor([[0.2325, 0.5127, 0.0945, 0.7237],
        [0.4663, 0.1062, 0.2486, 0.2106],
        [0.7606, 0.1446, 0.3771, 0.7895]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
#Set random seed
RANDOM_SEED = 42
torch.manual_seed(RANDOM_SEED)
random_tensor_c = torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
random_tensor_d = torch.rand(3,4)
print(random_tensor_c)
print(random_tensor_d)
print(random_tensor_c == random_tensor_d)


tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


##Running Tensors and pytorch objects on the GPUs (and making faster computations)
